### ISSUE TITLE
Question: How to get the embeddings of a list of SMILES strings

### ISSUE THREAD

**Issue by phosseini** [thinng/GraphDTA#1]
I wonder if there's any easy way to get the embeddings of a set/list of SMILEs string using the pre-trained models? For example, let's say we have a list of SMILEs like [smile_1, smiles_2,...,smile_n] how can I get the corresponding embedding vectors of SMILES in this list using the pre-trained models?

**Comment by thinng** [comment]
Thanks phosseini!
The pre-trained models receive both drugs (as graph representation for SMILES  strings) and proteins (as sequences) as input and return the affinity of them. For what you ask, I guess any X2Vec models could help.

**Comment by XuanLin1991** [comment]
Hi, a solid work! I wonder GraphDTA can be used for classification tasks such as DTI? Thank you

**Comment by phosseini** [comment]
> Thanks phosseini!
> The pre-trained models receive both drugs (as graph representation for SMILES strings) and proteins (as sequences) as input and return the affinity of them. For what you ask, I guess any X2Vec models could help.

Thanks. I think `smile_to_graph` is what I was looking for.

**Comment by thinng** [comment]
> Hi, a solid work! I wonder GraphDTA can be used for classification tasks such as DTI? Thank you
Sorry for missing this. 
Yes it can.  DTI (interactions) is binary, showing if a pair of drug/target interacts or not. While DTA (affinity) refers to the strength of the interaction. A tweak on the output of the model would do the task.

**Comment by thinng** [comment]
> Hi, a solid work! I wonder GraphDTA can be used for classification tasks such as DTI? Thank you

Sorry for missing this.
Yes it can. DTI (interactions) is binary, showing if a pair of drug/target interacts or not. While DTA (affinity) refers to the strength of the interaction. A tweak on the output of the model would do the task.

**Comment by DBpackage** [comment]
Hi, I made a fork page. 
All model structures are same, only classification task is added.
GraphDTA model works with classification tasks well, too!
Hope that this would help someone who want to do classification with graphDTA

https://github.com/DBpackage/GraphDTA-DTI.git
