### ISSUE TITLE
How to use a trained model to predict a new data?

### ISSUE THREAD

**Issue by mallertian** [thinng/GraphDTA#2]
I now have some sequences of proteins and drugs but no affinity data between them. How can I predict the affinity between them through your method？How should I handle my data and how to call your method? Can you predict?  I don't know how to make this, please give me some methods, thank you!

**Comment by thinng** [comment]
Hi mallertian,

There are two steps:

1. Create data in pytorch format
python create_data.py

2. Predict affinity with pretrained models
python predict_with_pretrained_model.py

Cheers,
thinng

**Comment by mallertian** [comment]
> 
> 
> Hi mallertian,
> 
> There are two steps:
> 
>     1. Create data in pytorch format
>        python create_data.py
> 
>     2. Predict affinity with pretrained models
>        python predict_with_pretrained_model.py
> 
> 
> Cheers,
> thinng
Thank you. I think I know what to do
