### ISSUE TITLE
Missing key(s) in state_dict

### ISSUE THREAD

**Issue by ryan-224** [thinng/GraphDTA#5]
Hi,

When I tried to run python predict_with_pretrained_model.py, 
for the GATNet model, I got an exception shown as follows. How can I fix it?
![image](https://user-images.githubusercontent.com/58620549/84759479-5c640e00-aff9-11ea-8208-38fa1d0f73f0.png)

Many thanks!
Ryan

**Comment by thinng** [comment]
Hi Ryan,

I have just cloned this github repository to my local computer and it runs smoothly, as shown here: 
![image](https://user-images.githubusercontent.com/4929536/85610979-dd2aa600-b69a-11ea-9272-928b10633bed.png)

I wonder if you followed the step-by-step guideline, say creating an environment variable and creating data in pytorch format before running predict_with_pretrained_model.py

Cheers,
Thin.

**Comment by zhenglz** [comment]
I have encountered the same error, and I just followed the protocol.

`predicting for  test.csv.pt  using  GATNet
loading model file:  ../pretrained/model_GATNet_davis.model
Traceback (most recent call last):
  File "../inference.py", line 70, in <module>
    model.load_state_dict(torch.load(model_file_name))
  File "/data1/zlzzheng/apps/anaconda3/envs/geometric/lib/python3.8/site-packages/torch/nn/modules/module.py", line 829, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GATNet:
        Missing key(s) in state_dict: "gcn1.att_l", "gcn1.att_r", "gcn1.lin_l.weight", "gcn1.lin_r.weight", "gcn2.att_l", "gcn2.att_r", "gcn2.lin_l.weight", "gcn2.lin_r.weight". 
        Unexpected key(s) in state_dict: "gcn1.weight", "gcn1.att", "gcn2.weight", "gcn2.att". `

**Comment by thinng** [comment]
Hi,

I have just cloned this github repository to my local computer and it runs
smoothly, as shown here:

[image: image]
<https://user-images.githubusercontent.com/4929536/85610979-dd2aa600-b69a-11ea-9272-928b10633bed.png>

I wonder if you followed the step-by-step guideline, say creating an
environment variable and creating data in pytorch format before running
predict_with_pretrained_model.py

Cheers,
Thin.

**Comment by MherMatevosyan** [comment]
Hi,

I encountered the same problem. It seems that problem comes from the version of ```pytorch_geometric```. I switched to 1.4.3 (which is the last version that has the same state_dict keys as pre-trained models) and it worked.
![graphdta-geo-143](https://user-images.githubusercontent.com/29042139/108712102-bc6b6680-752f-11eb-9f1c-b92f11d0732d.png)

However, the results seem to be inconsistent, as CI is much lower than it should be. 
Could you, please, help find out what's wrong?
I can share the google colab, in which I have run the code if needed.

**Comment by CuongVoThanh** [comment]
Hi team,

I also got the results, which CI is lower than yours. (with pretrained_models like @MherMatevosyan )
Could you please help us figure out what the problem is that?

Thanks in advance.
