### ISSUE TITLE
Confusion about the data process code

### ISSUE THREAD

**Issue by WangPenglei717** [thinng/GraphDTA#6]
Hi, I’m a little confused about the code in create_data.py:
![捕获](https://user-images.githubusercontent.com/59304127/86340624-c6caae80-bc87-11ea-9580-f4b6e2b2903c.PNG)

![捕获1](https://user-images.githubusercontent.com/59304127/86340914-2de86300-bc88-11ea-927e-ce2ea9335c23.PNG)
This seems to indicate that the number 0 represents both the character 'A' and the default value. Whether this will have an impact on the network's prediction results?

**Comment by thinng** [comment]
Good catch! Thanks!
 
Have changed the line 101 from
seq_dict = {v:i for i,v in enumerate(seq_voc)}
to
seq_dict = {v:(i+1) for i,v in enumerate(seq_voc)}

The result is quite similar though.

**Comment by WangPenglei717** [comment]
Get it. Thanks a lot!
