### ISSUE TITLE
How to change paired data into metrics Y

### ISSUE THREAD

**Issue by xuzhang5788** [thinng/GraphDTA#8]
Thank you for your repo. 

If my data set is like 

SMILES                         Protein sequence                     affinity 
CC1=C2C.....CC=C4)N MKKFFDSRR.....LLLVDQLIDL 7.365
CC1=C2C.....CC=C4) NSADAQSFLN.....MYTPHTVLQ 4.999

Do you have a function to change this to Y?

**Comment by thinng** [comment]
Y is the last column, or affinity.

**Comment by xuzhang5788** [comment]
In your code, Y is a matrix, I want to know how to make this matrix from the pair dataset. In the Y matrix, there are many empty elements.  I want to know how to make this lookup table. Thanks

**Comment by thinng** [comment]
Hi,
To compare our proposed methods with DeepDTA, we used the same dataset and the same splits provided at https://github.com/hkmztrk/DeepDTA/tree/master/data, where Y is a matrix.  We had to turn it back to the triple format, as shown in https://github.com/thinng/GraphDTA/blob/master/create_data.py.
