### ISSUE TITLE
how to prevent overfitting?

### ISSUE THREAD

**Issue by xuzhang5788** [thinng/GraphDTA#9]
I saw your epochs=1000 and you didn't set early stopping. So, how do you prevent overfitting for such large epochs? Thanks.

In addition, I don't think you can use your test dataset to guide your training (training.py). Normally, when you train your model, you can't touch the test dataset. Otherwise, it is overfitting and can not have a generalized model.  Maybe your training_validation.py is the right way to possibly have a generalized model.

In your paper, your results are better than DeepDTA and also WideDTA, I felt a little bit unsure if using a totally new test dataset.

**Comment by thinng** [comment]
Yes. training_validation.py could help avoid overfit.

**Comment by xuzhang5788** [comment]
I saw you also used your testing dataset to guide your training in your training_validation.py. So I think you have data leakage.

**Comment by thinng** [comment]
Could you please show me where in https://github.com/thinng/GraphDTA/blob/master/training_validation.py
testing is used to guide training? Thanks!

**Comment by xuzhang5788** [comment]
Sorry, I reread your code, it looks okay.
